let statement =
  "The quote 'There is no exercise better for the heart than reaching down and lifting people up.' by John Holmes teaches us to help one another.";
console.log(statement);

let quote =
  "Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.";
console.log(quote);

let string = "10";
let num = 10;
console.log(string == num);

let sentence = "python and jargon";
console.log(sentence.includes("on"));

let course = "i hope this course is not full of jargon";
console.log(course.includes("jargon"));

let because =
  "You cannot end a sentence with because because because is a conjunction";
console.log(because.substr(31, 23));
