// 1.
let statement =
  "The quote 'There is no exercise better for the heart than reaching down and lifting people up.' by John Holmes teaches us to help one another.";
console.log(statement);
// 2.
let quote =
  "Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.";
console.log(quote);
// 3.
let string = "10";
let num = 10;
console.log(string == num);
// 4.
let number = parseFloat(9.8);
console.log(Math.round(number));
// 5.
let sentence = "python and jargon";
console.log(sentence.includes("on"));
// 6.
let course = "i hope this course is not full of jargon";
console.log(course.includes("jargon"));

// 7.
let numb = Math.floor(Math.random() * 101);
console.log(numb);
// 8.
numb = Math.floor(Math.random() * 51) + 50;
console.log(numb);
// 9.
numb = Math.floor(Math.random() * 256);
console.log(numb);
// 10.
let m = Math.floor(Math.random() * 10);
console.log("javascript".charAt(m));
// 11.
let numbers = "1 1 1 1 1\n2 1 2 4 8\n3 1 3 9 27\n4 1 4 16 64\n5 1 5 25 125";
console.log(numbers);

// 12.
let because =
  "You cannot end a sentence with because because because is a conjunction";
console.log(because.substr(31, 23));
